sudo:
  required

services:
  - docker

language: java

jdk:
  - openjdk11

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: vadimeladii
    token:
      secure: 0b5a15b588a28eeff15e5287acbb6afdef3e3c7a

after_success:

   #LOGIN
  - docker login -u $D_USER -p $D_PASS

   #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

   #VESTA-API
  - export VESTA_API=vadimeladii7/vesta-api
  - docker build -t $VESTA_API:$COMMIT ./
  - docker tag $VESTA_API:$COMMIT $VESTA_API:$TAG
  - docker push $VESTA_API